-- Add SystemConfig table
CREATE TABLE "system_config" (
  "id" TEXT PRIMARY KEY,
  "adminId" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "value" JSONB NOT NULL,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY ("adminId") REFERENCES "user_metadata"("id")
);

CREATE UNIQUE INDEX "system_config_unique_key" ON "system_config" ("key");

-- Seed default values (assume admin ID exists, replace with actual)
INSERT INTO "system_config" ("id", "adminId", "key", "value") VALUES
('sys-001', (SELECT id FROM "user_metadata" WHERE role = 'ADMIN' LIMIT 1), 'request_expiry_days', '30'::jsonb),
('sys-002', (SELECT id FROM "user_metadata" WHERE role = 'ADMIN' LIMIT 1), 'pdf_footer_text', '"Generated by GOP Automation System. For insurance pre-authorisation only."'::jsonb),
('sys-003', (SELECT id FROM "user_metadata" WHERE role = 'ADMIN' LIMIT 1), 'audit_log_retention_days', '730'::jsonb);

-- Add failedAt to Notification
ALTER TABLE "notifications" ADD COLUMN "failedAt" TIMESTAMPTZ;

-- Add GOPRequest model (minimal for FKs)
CREATE TABLE "gop_requests" (
  "id" TEXT PRIMARY KEY,
  "status" TEXT NOT NULL, -- Will add enum later
  "patientId" TEXT NOT NULL,
  "insurerId" TEXT NOT NULL,
  "assignedDoctorId" TEXT,
  "formData" JSONB,
  "submittedAt" TIMESTAMPTZ,
  "approvedAt" TIMESTAMPTZ,
  "rejectedAt" TIMESTAMPTZ,
  "rejectedReason" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY ("insurerId") REFERENCES "insurer_config"("id"),
  FOREIGN KEY ("assignedDoctorId") REFERENCES "user_metadata"("id")
);

CREATE INDEX "gop_requests_status" ON "gop_requests" ("status");
CREATE INDEX "gop_requests_patient" ON "gop_requests" ("patientId");

-- DOWN (no rollback for audit data)
-- DROP INDEX IF EXISTS "gop_requests_patient";
-- DROP INDEX IF EXISTS "gop_requests_status";
-- DROP TABLE IF EXISTS "gop_requests";
-- ALTER TABLE "notifications" DROP COLUMN IF EXISTS "failedAt";
-- DELETE FROM "system_config" WHERE "key" IN ('request_expiry_days', 'pdf_footer_text', 'audit_log_retention_days');
-- DROP INDEX IF EXISTS "system_config_unique_key";
-- DROP TABLE "system_config";

